{% set name = "copulas" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copulas-{{ version }}.tar.gz
  sha256: 5aab94fdc5f933227e6a0775422e1c593234f3d021006be91c33ed180097aac1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.12
  run:
    - matplotlib-base >=3.4.0,<4
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - python >=3.8,<3.12
    - scipy >=1.5.4,<2

test:
  imports:
    - copulas
    - copulas.bivariate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/Copulas
  summary: Create tabular synthetic data using copulas-based modeling.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
