{% set name = "copulas" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copulas-{{ version }}.tar.gz
  sha256: 55cee8d2d0017b7124c4dbbd034e9a044528de13e4c4b0c79b43b8d35c49b764

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.13
  run:
    - numpy >=1.21.0
    - pandas >=1.4.0
    - plotly >=5.10.0
    - python >=3.8,<3.13
    - scipy >=1.7.3

test:
  imports:
    - copulas
    - copulas.bivariate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/Copulas
  summary: Create tabular synthetic data using copulas-based modeling.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
