{% set name = "copulas" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copulas-{{ version }}.tar.gz
  sha256: e0761d00a934d2fe9d56cf3cb955ba23b01e6103f965111a02825d45c4719e9f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.10
  run:
    - matplotlib-base >=3.2.0,<4
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - python >=3.6,<3.10
    - scipy >=1.5.4,<2

test:
  imports:
    - copulas
    - copulas.bivariate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/Copulas
  summary: A python library for building different types of copulas and using them for sampling.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rdt
