{% set name = "copulas" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copulas-{{ version }}.tar.gz
  sha256: fa38b4b5f14582a71242f1de6bada4485f9bd4adc50c6f6571f2c121d5a57c12

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.7,<3.12
  run:
    - matplotlib-base >=3.4.0,<4
    - numpy >=1.20.0,<2
    - pandas >=1.1.3,<2
    - python >=3.7,<3.12
    - scipy >=1.5.4,<2

test:
  imports:
    - copulas
    - copulas.bivariate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/Copulas
  summary: A python library for building different types of copulas and using them for sampling.
  license: BSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rdt
