{% set name = "copulas" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/copulas-{{ version }}.tar.gz
  sha256: a50f411dadfeb28b152097a6995919c03d07c33133035999f61d776bb6f4d005

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python {{ python_min }}
  run:
    - numpy >=1.21.0
    - pandas >=1.4.0
    - plotly >=5.10.0
    - python >={{ python_min }},<3.14
    - scipy >=1.7.3

test:
  imports:
    - copulas
    - copulas.bivariate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sdv-dev/Copulas
  summary: Create tabular synthetic data using copulas-based modeling.
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
